# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# Documentation for config on the official website
# https://sw.kovidgoyal.net/kitty/conf/

# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts

font_family      Hack Nerd Font 
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12

#: Window layout

window_padding_width 10

# hide_window_decorations yes

#: Tab bar

tab_bar_edge top

#: The foreground and background colors.

background #181825

background_opacity 0.9

# background_image ../../images/flatppuccin.jpg

# background_image_layout cscaled

# background_tint 0.9

# Key maps
map ctrl+shift+left move_window left
map ctrl+shift+up move_window up
map ctrl+shift+right move_window right
map ctrl+shift+down move_window down


