# Configuration for Alacritty

general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]

padding = { x = 30, y = 5 }
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11

[colors.primary]

background = "#000000"